# Generated by Django 5.2.4 on 2025-08-01 13:02

import ckeditor.fields
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(default=products.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(default=products.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=products.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descrição')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Preço')),
                ('price_decimal_places', models.IntegerField(default=2, verbose_name='Casas decimais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prod_brand', to='products.brand')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.stock')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
