# Generated by Django 5.2.4 on 2025-08-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'estoque', 'verbose_name_plural': 'estoque'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='products.product'),
        ),
    ]
