# Generated by Django 5.2.4 on 2025-08-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade mínima'),
        ),
    ]
